---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: blue-route
spec:
  parentRefs:
    - name: http
      namespace: traefik
    - name: blue
      kind: Service
      group: core
      port: 80
  hostnames:
    - "blue.localhost"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: blue
          port: 80
